
CREATE TABLE TB_TODO (
  ID          INTEGER PRIMARY KEY,
  DESCRIPTION VARCHAR(30)
);

CREATE TABLE TB_USER (
  ID          INTEGER PRIMARY KEY,
  FIRST_NAME VARCHAR(30),
  LAST_NAME VARCHAR(30),
  USERNAME VARCHAR(30)
);