
INSERT INTO TB_TODO VALUES (1, 'MYBATIS IS COOL');
INSERT INTO TB_TODO VALUES (2, 'I LOVE ORB');
INSERT INTO TB_TODO VALUES (3, 'WRITE MORE CODE WITH MYBATIS');


INSERT INTO TB_USER (id,FIRST_NAME,LAST_NAME,USERNAME) VALUES (1, 'Unit','Test','UNIT_TEST');
INSERT INTO TB_USER (id,FIRST_NAME,LAST_NAME,USERNAME) VALUES (2, 'hm','bktsh','bktsh');
